<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class Post extends Model
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::saving(function ($obj) {
            $obj->slug = str_slug($obj->slug);
        });
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class, 'post_has_tags', 'post_id', 'tag_id');
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class, 'post_has_categories', 'post_id', 'category_id');
    }

    public function comments()
    {
        return $this->morphMany(Comments::class, 'item');
    }

    public function scopeOrder(Builder $builder, $order = false)
    {
        if($order){
            return $builder
                ->orderBy('created_at', 'DESC')
                ->orderBy('id', 'DESC');
        }
    }

    public function getImageAttribute(){
        return $this->cover ?? asset("/storage/post/". $this->id. ".jpg");
    }
}
